-- Online storefront: backend stays core, POS + online are frontends on same tables
CREATE TYPE "OrderChannel" AS ENUM ('pos', 'online');
CREATE TYPE "Fulfilment" AS ENUM ('pickup', 'delivery');
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'pending';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'confirmed';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'packed';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'out_for_delivery';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'delivered';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'cancelled';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "isOnlineEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "pickupEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "deliveryEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "codEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "deliveryFee" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "freeDeliveryAbove" DECIMAL(12,2);
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "minOrderAmount" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "onlineNote" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "isOnline" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "onlinePrice" DECIMAL(12,2);
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "imageUrl" TEXT;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "passwordHash" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "channel" "OrderChannel" NOT NULL DEFAULT 'pos';
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "fulfilment" "Fulfilment";
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "deliveryAddress" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "deliveryPhone" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "notes" TEXT;
CREATE INDEX IF NOT EXISTS "Shop_city_idx" ON "Shop"("city");
CREATE INDEX IF NOT EXISTS "Shop_isOnlineEnabled_idx" ON "Shop"("isOnlineEnabled");
CREATE INDEX IF NOT EXISTS "Product_shopId_isOnline_idx" ON "Product"("shopId", "isOnline");
CREATE INDEX IF NOT EXISTS "Order_shopId_channel_idx" ON "Order"("shopId", "channel");
CREATE INDEX IF NOT EXISTS "Order_shopId_channel_status_idx" ON "Order"("shopId", "channel", "status");
CREATE INDEX IF NOT EXISTS "Customer_shopId_email_idx" ON "Customer"("shopId", "email");
